# Generated by Django 4.0.2 on 2024-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual')], default='physical', max_length=20),
        ),
    ]
