# Generated by Django 4.0.2 on 2024-03-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_practice', '0003_ebook_remove_book_download_link_remove_book_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ebook',
            field=models.ManyToManyField(to='model_practice.EBook'),
        ),
    ]
