# Generated by Django 5.0.4 on 2024-04-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration_practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
    ]
